In [5]:
import numpy as np

In [3]:
n1=np.array([])
n1

array([], dtype=float64)

In [5]:
list1=[1,4,6,8,9,10]
n2=np.array(list1)
n2

array([ 1,  4,  6,  8,  9, 10])

In [7]:
n2.dtype

dtype('int32')

In [9]:
t1=(5,6,7,8,9)
n3=np.array(t1)
n3

array([5, 6, 7, 8, 9])

In [13]:
n4=np.zeros((3,3))
n4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
n5=np.ones((2,3))
n5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
n5.dtype

dtype('float64')

In [23]:
n6=np.full((3,4),9)
n6

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [29]:
n7=np.arange(11,20).reshape(3,3)
n7

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
n8=np.random.randint(11,20,25).reshape(5,5)
n8

array([[18, 17, 16, 18, 11],
       [14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15],
       [15, 14, 17, 17, 16],
       [14, 18, 15, 15, 16]])

In [17]:
n9=np.linspace(1,10,6).reshape(3,2)
n9

array([[ 1. ,  2.8],
       [ 4.6,  6.4],
       [ 8.2, 10. ]])

In [19]:
n8.dtype

dtype('int32')

In [21]:
n9.dtype

dtype('float64')

In [23]:
n9.size

6

In [25]:
n9.shape

(3, 2)

In [27]:
n9.ndim

2

In [35]:
n10=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
n10

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
n10.ndim

3

In [39]:
n10.shape

(2, 3, 3)

In [41]:
n8

array([[13, 11, 16, 11, 13],
       [14, 11, 14, 17, 11],
       [12, 14, 12, 11, 15],
       [11, 15, 16, 14, 17],
       [19, 11, 16, 11, 19]])

In [1]:
# Scalar Addition
n8+1

NameError: name 'n8' is not defined

In [45]:
n8*2

array([[26, 22, 32, 22, 26],
       [28, 22, 28, 34, 22],
       [24, 28, 24, 22, 30],
       [22, 30, 32, 28, 34],
       [38, 22, 32, 22, 38]])

In [47]:
np.sum(n8)

344

In [7]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,3,4,5])

In [55]:
np.sum([a,b])

40

In [57]:
np.sum([a,b,], axis=0)

array([ 7,  9,  6,  8, 10])

In [59]:
np.sum([a,b], axis=1)

array([15, 25])

In [63]:
print(n8)
np.sum(n8, axis=0)

[[13 11 16 11 13]
 [14 11 14 17 11]
 [12 14 12 11 15]
 [11 15 16 14 17]
 [19 11 16 11 19]]


array([69, 62, 74, 64, 75])

In [65]:
print(n8)
np.sum(n8, axis=1)

[[13 11 16 11 13]
 [14 11 14 17 11]
 [12 14 12 11 15]
 [11 15 16 14 17]
 [19 11 16 11 19]]


array([64, 67, 64, 73, 76])

In [67]:
np.mean(n8)

13.76

In [69]:
np.mean(n8, axis=0)

array([13.8, 12.4, 14.8, 12.8, 15. ])

In [71]:
np.mean(n8, axis=1)

array([12.8, 13.4, 12.8, 14.6, 15.2])

In [73]:
np.median(n8)

14.0

In [75]:
np.median(n8, axis=0)

array([13., 11., 16., 11., 15.])

In [77]:
np.std(n8)

2.5499803920814763

In [79]:
print(a)
print(b)

[1 2 3 4 5]
[6 7 3 4 5]


In [81]:
np.equal(a,b)

array([False, False,  True,  True,  True])

In [85]:
np.array_equal(a,b)

False

In [87]:
c=np.array([1,2,3,4,5])

In [89]:
np.array_equal(a,c)

True

In [9]:
print(a)
print(b)

[1 2 3 4 5]
[6 7 3 4 5]


In [13]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 3, 4, 5])

In [17]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [19]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 3, 4, 5])

In [21]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 3],
       [4, 4],
       [5, 5]])

In [23]:
np.row_stack((a,b))

array([[1, 2, 3, 4, 5],
       [6, 7, 3, 4, 5]])

In [27]:
np.intersect1d(a,b)

array([3, 4, 5])

In [29]:
np.setdiff1d(a,b)

array([1, 2])

In [31]:
print(a)
print(b)

[1 2 3 4 5]
[6 7 3 4 5]


In [33]:
np.setdiff1d(b,a)

array([6, 7])

In [37]:
np.save('arr1',n8)

In [39]:
n11=np.load('arr1.npy')
n11

array([[18, 17, 16, 18, 11],
       [14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15],
       [15, 14, 17, 17, 16],
       [14, 18, 15, 15, 16]])

In [41]:
#slicing
n11[1:3,:]

array([[14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15]])

In [43]:
n11[:,3:]

array([[18, 11],
       [15, 11],
       [12, 15],
       [17, 16],
       [15, 16]])

In [45]:
n11[:,-2:]

array([[18, 11],
       [15, 11],
       [12, 15],
       [17, 16],
       [15, 16]])

In [47]:
n11

array([[18, 17, 16, 18, 11],
       [14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15],
       [15, 14, 17, 17, 16],
       [14, 18, 15, 15, 16]])

In [49]:
n11[:2,:2]
# array_name[start_row:end_row,start_column:end_column]

array([[18, 17],
       [14, 13]])

In [51]:
n11

array([[18, 17, 16, 18, 11],
       [14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15],
       [15, 14, 17, 17, 16],
       [14, 18, 15, 15, 16]])

In [55]:
#n11[-2:,-2:]
n11[3:,3:]


array([[17, 16],
       [15, 16]])

In [57]:
n11

array([[18, 17, 16, 18, 11],
       [14, 13, 19, 15, 11],
       [18, 12, 16, 12, 15],
       [15, 14, 17, 17, 16],
       [14, 18, 15, 15, 16]])

In [61]:
#n11[:2,3:]
n11[:2,-2:]

array([[18, 11],
       [15, 11]])