In [1]:
import numpy as np

In [5]:
n1=np.array([])
n1

array([], dtype=float64)

In [7]:
n1=np.array([1,3,5,8,10])
n1

array([ 1,  3,  5,  8, 10])

In [9]:
n1.dtype

dtype('int32')

In [13]:
t1=(5,6,7,8,9)
n2=np.array(t1)
n2

array([5, 6, 7, 8, 9])

In [15]:
n3=np.zeros((3,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
n4=np.ones((2,3))
n4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
n5=np.full((3,3),7)
n5

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [25]:
n6=np.arange(11,20).reshape(3,3)
n6

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
n7=np.random.randint(1,100,15).reshape(5,3)
n7

array([[51, 72, 38],
       [91, 60, 53],
       [ 1, 31, 79],
       [76, 55, 12],
       [ 2, 88, 13]])

In [37]:
n7.ndim

2

In [39]:
n7.size

15

In [41]:
n7.shape

(5, 3)

In [43]:
sum(n7)

array([221, 306, 195])

In [51]:
n7.max()

91

In [53]:
n7.min()

1

In [13]:
#n8=np.linspace(11,20,4).reshape(2,2)
n8=np.linspace(11,20,4)
n8.shape=(2,2)
n8

array([[11., 14.],
       [17., 20.]])

In [15]:
# scalar oprations
n9=np.random.randint(11,20,6)
n9

array([16, 15, 12, 15, 14, 15])

In [17]:
n9+2

array([18, 17, 14, 17, 16, 17])

In [19]:
n9*2

array([32, 30, 24, 30, 28, 30])

In [21]:
n9-2

array([14, 13, 10, 13, 12, 13])

In [23]:
n9.shape=(3,2)
n9

array([[16, 15],
       [12, 15],
       [14, 15]])

In [25]:
np.sum(n9)

87

In [27]:
np.sum(n9, axis=0)

array([42, 45])

In [29]:
np.sum(n9, axis=1)

array([31, 27, 29])

In [31]:
np.mean(n9)

14.5

In [33]:
np.mean(n9, axis=0)

array([14., 15.])

In [35]:
np.mean(n9, axis=1)

array([15.5, 13.5, 14.5])

In [37]:
np.median(n9)

15.0

In [39]:
np.std(n9)

1.2583057392117916

In [47]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,6,7,8])

In [49]:
np.equal(a,b)

array([ True,  True, False, False, False])

In [51]:
np.array_equal(a,b)

False

In [53]:
c=np.array([1,2,3,4,5])

In [55]:
np.array_equal(a,c)

True

In [57]:
print(a)
print(b)

[1 2 3 4 5]
[1 2 6 7 8]


In [59]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [1, 2, 6, 7, 8]])

In [61]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 1, 2, 6, 7, 8])

In [89]:
#np.column_stack((a,b))
#np.row_stack((a,b))
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 1, 2, 6, 7, 8])

In [65]:
np.intersect1d(a,b)

array([1, 2])

In [67]:
np.setdiff1d(a,b)

array([3, 4, 5])

In [69]:
np.setdiff1d(b,a)

array([6, 7, 8])

In [71]:
np.save('my_arr1',n9)

In [73]:
n10=np.load('my_arr1.npy')
n10

array([[16, 15],
       [12, 15],
       [14, 15]])